### ISSUE TITLE
Want to add solution of Best time to buy and sell stock ii in java 

### ISSUE THREAD

**Issue by rajeshkumar2024** [yashrajyash18/hacktoberfest2020#24]
Problem Link - https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/
@yashrajyash18 I want to add solution for this problem under HackOctober 2022. Please assign me this issue.

**Comment by coolsand19** [comment]
I want to add solution for this problem under HackOctober 2022. Please assign me this issue.

**Comment by psrp7** [comment]
please assign me this task

**Comment by yashrajyash18** [comment]
@coolsand19 you can add the C++ file

**Comment by yashrajyash18** [comment]
@psrp7 Can you do this in any other language except C++ and Java, so I can assign you this work

**Comment by psrp7** [comment]
ok
