### ISSUE TITLE
I want to add new section of  System Design So People Can benefit from it.

### ISSUE THREAD

**Issue by coolsand19** [yashrajyash18/hacktoberfest2020#46]

**Comment by coolsand19** [comment]
Hello Sir,

I have already contribute one time and I have gone through the Repository and given Instruction. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Sandeep Kumar.

**Comment by yashrajyash18** [comment]
@coolsand19 I've assigned you the task, happy coding :)

**Comment by yashrajyash18** [comment]
@coolsand19 when will you submit your work, do it ASAP else I'll close this issue.

**Comment by coolsand19** [comment]
ok I will do it tomorrow

**Comment by yashrajyash18** [comment]
@coolsand19 when will your tomorrow come? 
complete your work by tonight.

**Comment by yashrajyash18** [comment]
@coolsand19 sorry to say that you haven't submitted your work on time that's why I'm closing this pr.
